[package]
name = "test_helpers"
version = "0.1.0-alpha"
authors = ["Brushfam <varex.silver@727.ventures>"]
edition = "2021"

[lib]
name = "test_helpers"
path = "lib.rs"

[profile.dev]
codegen-units = 16
